from PIL import Image

class QRCode:
    def __init__(self, box_size: int, border: int) -> None: ...
    def add_data(self, string: str) -> None: ...
    def make(self) -> None: ...
    def print_ascii(self) -> None: ...
    def make_image(self) -> Image.Image: ...
