name: Build appimage

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: christofsteel/syng
      - name: Install poetry
        run: pip install poetry
      - name: Extract version from Poetry
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
        shell: bash
      - name: Preparing Build dir
        run: |
          mkdir -p app/bin
          cp "${{ github.workspace }}/resources/appimage/build.sh" app/build.sh
          cp "${{ github.workspace }}/resources/appimage/bin/syng" app/bin/
          cp "${{ github.workspace }}/resources/appimage/bin/yt-dlp" app/bin/
      - name: Building AppDir
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/christofsteel/syng-appimage-builder:main 
          options: -v "${{ github.workspace }}"/app:/app
          run: |
            /app/build.sh 
            export APPIMAGE_EXTRACT_AND_RUN=1
            /app/linuxdeploy-x86_64.AppImage --plugin qt --appdir /app/AppDir --output appimage
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Syng Version ${{ env.VERSION }} AppImage
          path: "${{ github.workspace }}/app/Syng-x86_64.AppImage"
